---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fluentd-splunk
  namespace: logging
spec:
  selector:
    matchLabels:
      app: fluentd-splunk
  template:
    metadata:
      labels:
        app: fluentd-splunk
    spec:
      serviceAccount: fluentd
      serviceAccountName: fluentd
      imagePullSecrets:
      - name: regcred
      containers:
      - name: fluentd-splunk
        image: devopsdemo557.azurecr.io/system/fluentd-splunk:1
        imagePullPolicy: Always
        # env:
        #   - name: FLUENT_CONTAINER_TAIL_PARSER_TYPE
        #     value: "cri"
        # command:
        #   - '/bin/sh'
        #   - '-c'
        #   - '/run.sh >>/dev/null 2>&1 '
        # resources:
        #   limits:
        #     memory: 512Mi
        #     cpu: 256m
        #   requests:
        #     cpu: 100m
        #     memory: 200Mi
        volumeMounts:
        - name: varlog
          mountPath: /var/log
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: fluentd-conf-splunk
          # mountPath: /etc/fluent
          mountPath: /fluentd/etc

      terminationGracePeriodSeconds: 30
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: fluentd-conf-splunk
        configMap:
          name: fluentd-conf-splunk