apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: istio-ingress
spec:
  acme:
    # The ACME server URL
    server: https://acme-v02.api.letsencrypt.org/directory
    # Email address used for ACME registration
    email: giangtlt@fpt.com
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      # An empty 'selector' means that this solver matches all domains
      - selector: {}
        http01:
          ingress:
            class: istio
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api-cert
  namespace: istio-ingress
spec:
  secretName: api-cert
  dnsNames:
  - api.yanyicivic.com
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: vault-cert
  namespace: istio-ingress
spec:
  secretName: vault-cert
  dnsNames:
  - vault.yanyicivic.com
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io
---

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: fe-cert
  namespace: istio-ingress
spec:
  secretName: fe-cert
  dnsNames:
  - shop.yanyicivic.com
  issuerRef:
    name: letsencrypt-prod
    kind: Issuer
    group: cert-manager.io