---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: https
  namespace: istio-ingress
spec:
  selector:
    istio: ingress
  servers:
  - port:
      number: 443
      name: httpsapi
      protocol: HTTPS
    hosts:
    - "api.yanyicivic.com"
    tls:
      credentialName: api-cert
      mode: SIMPLE
  - port:
      number: 80
      name: httpapi
      protocol: HTTP
    hosts:
    - "api.yanyicivic.com"
    tls:
      httpsRedirect: true
  
  - port:
      number: 443
      name: httpsvault
      protocol: HTTPS
    hosts:
    - "vault.yanyicivic.com"
    tls:
      credentialName: vault-cert
      mode: SIMPLE
  - port:
      number: 80
      name: httpvault
      protocol: HTTP
    hosts:
    - "vault.yanyicivic.com"
    tls:
      httpsRedirect: true
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: all-traffic
  namespace: istio-ingress
spec:
  host: "*"
  trafficPolicy:
    loadBalancer:
      simple: ROUND_ROBIN