---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
  # annotations:
  #   secret.reloader.stakater.com/reload: "demosecret"
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "demo-sa"
      imagePullSecrets:
      - name: regcred
      containers:
      - name: devops-container
        image: devopsdemo557.azurecr.io/dev/api:tag
        # volumeMounts:
        # - name: secrets-store01-inline
        #   mountPath: "/mnt/secrets-store"
        #   readOnly: true
        ports:
        - containerPort: 80
        env:
          - name: KEYVAULT_URL
            value: https://demo.vault.azure.net/
          - name: AZURE_CLIENT_ID
            value: 064d951e-4e03-4759-9b5d-edddb364da36
          - name: AZURE_TENANT_ID
            value: f73ef2fd-2720-451a-b747-eb0a6630b23f
        # envFrom:
        # - secretRef:
        #     name: demosecret
      # volumes:
      # - name: secrets-store01-inline
      #   csi:
      #     driver: secrets-store.csi.k8s.io
      #     readOnly: true
      #     volumeAttributes:
      #       secretProviderClass: "azure-kvname-wi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: api-vs
  namespace: default
spec:
  hosts:
  - "api.yanyicivic.com"
  gateways:
  - istio-ingress/https
  http:
  - route:
    - destination:
        host: "api-svc"
        port:
          number: 80