---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: default
  annotations:
    secret.reloader.stakater.com/reload: "qualgosecret"
  labels:
    app: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: "qualgo-sa"
      imagePullSecrets:
      - name: regcred
      containers:
      - name: devops-container
        image: devopsqualgo557.azurecr.io/dev/api:tag
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
        ports:
        - containerPort: 80
        env:
          - name: KEYVAULT_URL
            value: https://qualgo.vault.azure.net/
          - name: AZURE_CLIENT_ID
            value: 064d951e-4e03-4759-9b5d-edddb364da36
          - name: AZURE_TENANT_ID
            value: f73ef2fd-2720-451a-b747-eb0a6630b23f
          - name: API_MONGO_DB
            valueFrom:
              secretKeyRef:
                name: qualgosecret
                key: API_MONGO_DB

          - name: API_MONGO_PWS
            valueFrom:
              secretKeyRef:
                name: qualgosecret
                key: API_MONGO_PWS

          - name: API_MONGO_USER
            valueFrom:
              secretKeyRef:
                name: qualgosecret
                key: API_MONGO_USER

          - name: MONGO_HOST
            valueFrom:
              secretKeyRef:
                name: qualgosecret
                key: MONGO_HOST

          - name: MONGO_PORT
            valueFrom:
              secretKeyRef:
                name: qualgosecret
                key: MONGO_PORT

          - name: NEXT_PUBLIC_API_ENDPOINT
            valueFrom:
              secretKeyRef:
                name: qualgosecret
                key: NEXT_PUBLIC_API_ENDPOINT
        # envFrom:
        # - secretRef:
        #     name: qualgosecret
      volumes:
      - name: secrets-store01-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: "azure-kvname-wi"
---
apiVersion: v1
kind: Service
metadata:
  name: api-svc
  namespace: default
spec:
  selector:
    app: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---

