status_code = {
    0: "Lưu nháp",
    1: "Đã tạo",
    2: "Chuyển tin cho Bưu tá",
    3: "Đang xử lý",
    4: "Đang lấy hàng",
    5: "Lấy hàng không thành công",
    6: "Lấy hàng thành công",
    7: "Bưu cục đã nhận hàng",
    8: "Lấy hàng thất bại",
    9: "Hủy thu gom",
    10: "Đang vận chuyển",
    11: "Đã đến BC phát",
    12: "Đang giao hàng",
    13: "Chuyển tiếp",
    14: "Đã giao hàng",
    15: "Giao hàng không thành công",
    16: "Chờ để chuyển hoàn",
    17: "Đã duyệt hoàn",
    18: "Bắt đầu chuyển hoàn",
    19: "Hoàn thành công",
    20: "Đã trả hàng 1 phần",
    21: "Đã trả tiền COD",
    22: "Hủy giao hàng"
}
