import { AntdRegistry } from "@ant-design/nextjs-registry";
import "./globals.css";
import "./custom.css";
import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import { Providers } from "@/lib/providers";

const font = Open_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Shop Utrans",
  description: "Generated by thongnth",
};

const RootLayout = ({ children }: React.PropsWithChildren) => (
  <html lang="en">
    <body className={font.className}>
      <AntdRegistry>
        <Providers>
          {children}
        </Providers>
      </AntdRegistry>
    </body>
  </html>
);

export default RootLayout;
